package KieRule;
import com.springboot.example.entity.Order;


rule "HDFC based discount"

when
    orderObject : Order(cardType == "HDFC" && price > 10000);
then
System.out.println("==========Adding 10% discount for HDFC =============");
    orderObject.setDiscount(10);
end



rule "ICICI based discount"

when
    orderObject : Order(cardType == "ICICI" && price > 15000);
then
    System.out.println("==========Adding 08% discount for ICICI =============");
    orderObject.setDiscount(8);
end


rule "DBS based discount"

when
    orderObject : Order(cardType == "DBS" && price > 15000);
then
    System.out.println("==========Adding 15% discount for DBS =============");
    orderObject.setDiscount(15);
end