package rules

import com.kaleshrikant.drools.core.model.Person;

rule "Adult Check"
    when
        $person : Person( age >= 18)
    then
        System.out.println("----------------------------------");
        System.out.println("rule 'PersonFactInsertion'");
        System.out.println($person.getName() + " is an Adult");
end

rule "Minor Check"
    when
        $person : Person (age <= 18)
    then
        System.out.println($person.getName() + " is an Minor");
        System.out.println("----------------------------------");
        System.out.println();
end